# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-22 02:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='csv_header',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='table',
            name='example',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
