# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-08-07 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='picked_indicator',
            field=models.BooleanField(default=False),
        ),
    ]
