# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-05-10 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0002_auto_20190422_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='approval_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=5),
        ),
    ]
